"""Hub and dossier pages: the connective tissue of the vault, generated by Python.

Why: ledger notes are append-only, so an old note can never gain links. Instead, generated
hub pages link to every member, and entity dossiers (store, city, competitor) link the
records that mention them. Every page is then reachable from `map`, and related records
sit one hop from each other in Obsidian's graph. New ledger notes also get outgoing links
at creation (see related()).

Rebuilt after every filing and by `coffee lint --fix-index`. Never edit these pages by hand.
"""
from __future__ import annotations

import re
from pathlib import Path

from . import corrections
from .digest import META, chron
from .ledger import ledger_dir
from .util import note_problem, atomic_write, dump_frontmatter, page_fm, read_page, slugify, today

HUB_DIR = "wiki/hubs"
SKIP_DIRS = {".git", ".obsidian", ".coffee-work", "_vendor", "__pycache__", ".venv", ".pytest_cache", "tests", "scripts", "node_modules"}

COLLECTION_HUB = {
    "week": "hub-weeks", "store": "hub-stores", "city": "hub-cities", "competitor": "hub-competitors",
    "decision": "hub-decisions", "capital-allocation": "hub-capital", "loan": "hub-capital",
    "investment": "hub-capital", "acquisition": "hub-capital", "event": "hub-events",
    "catalog": "hub-catalog", "test": "hub-knowledge", "correction": "hub-corrections", "review": "hub-reviews", "menu-week": "hub-menu",
}
HUB_TITLES = {
    "hub-briefings": "Briefings", "hub-decisions": "Decisions", "hub-weeks": "Weeks", "hub-events": "Events", "hub-reviews": "Customer reviews", "hub-menu": "Menu by week",
    "hub-catalog": "Option catalog", "hub-stores": "Stores", "hub-cities": "Cities", "hub-competitors": "Competitors",
    "hub-capital": "Capital, loans, investments and acquisitions", "hub-knowledge": "Knowledge base",
    "hub-corrections": "Corrections", "hub-process": "Process decisions", "hub-rules": "Rules and documents", "hub-archive": "Archive and working files",
}


def md_files(v: Path):
    for p in v.rglob("*.md"):
        parts = p.relative_to(v).parts
        if any(part in SKIP_DIRS or part.startswith(".") for part in parts):
            continue
        yield p


def _text(fm: dict) -> str:
    return " ".join(str(val) for k, val in fm.items() if k not in META and val not in (None, "")) + " " + str(fm.get("title", ""))


def _load(folder: Path):
    out = []
    for p in sorted(folder.glob("20*.md")) + sorted(folder.glob("week-*.md")):
        fm, _ = read_page(p)
        if fm:
            out.append((p, fm))
    return out


class Registry:
    """Names of things that other records can mention."""

    def __init__(self, v: Path):
        self.v = v
        self.stores, self.cities, self.competitors, self.catalog = {}, {}, {}, {}
        for p, fm in _load(ledger_dir(v) / "stores"):
            name = str(fm.get("name") or fm.get("store") or "").strip()
            if name:
                slug = "store-" + slugify(name)
                self.stores.setdefault(slug, {"name": name, "notes": []})["notes"].append(p)
        for p, fm in _load(ledger_dir(v) / "cities"):
            name = str(fm.get("city") or fm.get("name") or "").strip()
            if name:
                self.cities.setdefault(name.lower(), {"name": name, "notes": []})["notes"].append(p)
        for p, fm in _load(ledger_dir(v) / "competitors"):
            name = str(fm.get("name") or fm.get("competitor") or "").strip()
            if name:
                self.competitors.setdefault(name.lower(), {"name": name, "notes": []})["notes"].append(p)
        counts = {}
        rows = []
        for p, fm in _load(ledger_dir(v) / "catalog"):
            name = str(fm.get("name") or "").strip()
            if name:
                counts[name.lower()] = counts.get(name.lower(), 0) + 1
                rows.append((p, fm, name))
        self.catalog_rows = rows
        self.unique_catalog = {n for n, c in counts.items() if c == 1 and len(n) >= 4}

    def store_aliases(self, name: str):
        base = name.lower()
        return {base, base.replace(" st", " street"), base.replace(" street", " st")}

    def mentions(self, text: str, exclude: str = ""):
        t = text.lower()
        out = []
        for slug, d in self.stores.items():
            if slug != exclude and any(a in t for a in self.store_aliases(d["name"])):
                out.append(slug)
        for key, d in self.cities.items():
            if key in t:
                out.append("hub-cities")
                break
        for key, d in self.competitors.items():
            if key in t:
                out.append(d["notes"][0].stem)
        for p, fm, name in self.catalog_rows:
            if name.lower() in self.unique_catalog and name.lower() in t and p.stem != exclude:
                out.append(p.stem)
        seen, ordered = set(), []
        for s in out:
            if s not in seen:
                seen.add(s)
                ordered.append(s)
        return ordered


def related(v: Path, target: str, fields: dict, reg=None):
    """(hub stem, [related stems]) for a record about to be written. Pass a Registry to avoid rebuilding it for every note."""
    hub = COLLECTION_HUB.get(target, "hub-knowledge")
    try:
        reg = reg or Registry(v)
    except Exception as _e:
        note_problem(__name__, _e)
        return hub, []
    text = " ".join(str(x) for x in fields.values())
    return hub, reg.mentions(text)[:8]


def _page(title: str, summary: str, lines: list, tags=None) -> str:
    fm = page_fm(title, summary, "hub", tags or ["hub"], status="final")
    return dump_frontmatter(fm) + "\n" + "\n".join(lines).rstrip() + "\n"


def _write(v: Path, stem: str, title: str, summary: str, lines: list):
    p = v / HUB_DIR / f"{stem}.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    text = _page(title, summary, lines)
    if not p.exists() or p.read_text(encoding="utf-8") != text:
        # keep the original creation date when regenerating
        if p.exists():
            old, _ = read_page(p)
            if old and old.get("date_created"):
                text = text.replace(f"date_created: '{today()}'", f"date_created: '{old['date_created']}'", 1)
        atomic_write(p, text)


def L(stem, label=None):
    return f"[[{stem}|{label}]]" if label else f"[[{stem}]]"


def _fmt(val):
    return f"{val:,}" if isinstance(val, int) else str(val)


def rebuild(v: Path):
    reg = Registry(v)
    ld = ledger_dir(v)
    cmap = corrections.corrected_map(v)

    # ---- briefings (chronological) ----
    b_lines = ["# Briefings", "", "Every answer, oldest first. Each one links the records it filed.", ""]
    briefs = sorted((v / "wiki" / "briefings").glob("*.md"), key=lambda x: x.stem)
    for p in briefs:
        fm, body = read_page(p)
        n = len(set(re.findall(r"\[\[([^\]|#]+)", body.split("## Ledger notes")[-1]))) if "## Ledger notes" in body else 0
        b_lines.append(f"- {L(p.stem)}: {(fm or {}).get('summary', '')} ({n} records){corrections.flag(p.stem, cmap)}")
    _write(v, "hub-briefings", "Briefings", "Every briefing in order.", b_lines)

    # ---- weeks ----
    w_lines = ["# Weeks", "", "Original weekly records and their amendments, in week order.", ""]
    weeks = {}
    for p, fm in _load(ld / "weeks"):
        weeks.setdefault(str(fm.get("week", "?")), []).append((p, fm))
    for wk in sorted(weeks, key=lambda k: (not k.isdigit(), int(k) if k.isdigit() else 0)):
        items = weeks[wk]
        facts = "; ".join(f"{k.replace('_', ' ')} {_fmt(val)}" for k, val in items[0][1].items() if k not in META and k != "week")[:200]
        w_lines.append(f"- **Week {wk}**: " + ", ".join(L(p.stem) for p, _ in items) + (f" ({facts})" if facts else ""))
    _write(v, "hub-weeks", "Weeks", "Weekly records in order.", w_lines)

    # ---- catalog ----
    chosen = set()
    for p, fm in _load(ld / "stores"):
        for cat, key in (("exterior", "exterior"), ("interior", "interior"), ("equipment", "espresso_machine"),
                         ("equipment", "brewer"), ("equipment", "blender")):
            if fm.get(key):
                chosen.add((cat, str(fm[key]).lower()))
    c_lines = ["# Option catalog", "", "Every option seen in the game, by category, with the price and stats shown on screen.", ""]
    by_cat = {}
    for p, fm, name in reg.catalog_rows:
        by_cat.setdefault(str(fm.get("category", "other")), []).append((p, fm, name))
    for cat in sorted(by_cat):
        c_lines += [f"## {cat.title()} ({len(by_cat[cat])})"]
        for p, fm, name in sorted(by_cat[cat], key=lambda t: t[2].lower()):
            bits = []
            for key in ("cost", "quality", "productivity"):
                if fm.get(key) not in (None, ""):
                    bits.append(f"{key} {_fmt(fm[key])}")
            star = " **(built)**" if (cat, name.lower()) in chosen else ""
            c_lines.append(f"- {L(p.stem, name)}: {', '.join(bits) or 'no stats shown'}{star}")
        c_lines.append("")
    _write(v, "hub-catalog", "Option catalog", "All catalog options by category.", c_lines)

    # ---- decisions ----
    d_lines = ["# Decisions", "", "Each decision with its amendments and the stores, competitors and options it mentions.", ""]
    groups = {}
    for p, fm in _load(ld / "decisions"):
        groups.setdefault(str(fm.get("decision") or p.stem), []).append((p, fm))
    for name in sorted(groups, key=lambda n: min(p.name for p, _ in groups[n])):
        d_lines.append(f"## {name}")
        for p, fm in groups[name]:
            ment = reg.mentions(_text(fm), exclude=p.stem)
            tail = f" Mentions: {', '.join(L(m) for m in ment)}." if ment else ""
            d_lines.append(f"- {L(p.stem, str(fm.get('op', 'append')) + ' ' + str(fm.get('date_created', '')))} (confidence {fm.get('confidence')}).{tail}{corrections.flag(p.stem, cmap)}")
        d_lines.append("")
    _write(v, "hub-decisions", "Decisions", "All decisions grouped by name.", d_lines)

    # ---- events ----
    e_lines = ["# Events", "", "Newsletter and news items, with any competitor they concern.", ""]
    for p, fm in _load(ld / "events"):
        ment = reg.mentions(_text(fm), exclude=p.stem)
        e_lines.append(f"- {L(p.stem)}: {fm.get('severity', '?')} severity, {fm.get('category', 'event')}." + (f" Mentions: {', '.join(L(m) for m in ment)}." if ment else "") + corrections.flag(p.stem, cmap))
    _write(v, "hub-events", "Events", "All events.", e_lines)

    # ---- menu by week ----
    m_lines = ["# Menu by week", "", "One record per week: every menu item with price, unit cost, margin and sales last week. Newest first.", ""]
    for p, fm in sorted(_load(ld / "menu-weeks"), key=lambda t: -int(str(t[1].get("week", 0)) or 0) if str(t[1].get("week", "")).isdigit() else 0):
        its = fm.get("items") or []
        top = sorted((i for i in its if str(i.get("sales", "")).isdigit()), key=lambda i: -int(i["sales"]))[:3]
        m_lines.append(f"- {L(p.stem)}: week {fm.get('week')}, {len(its)} items" + (", top sellers " + ", ".join(f"{i['name']} {i['sales']}" for i in top) if top else ""))
    _write(v, "hub-menu", "Menu by week", "Weekly menu records.", m_lines)

    # ---- customer reviews ----
    r_lines = ["# Customer reviews", "", "Every review the CEO has shown, one record each, newest week first. Ratings for price, product, service and atmosphere are on the store records.", ""]
    revs = sorted(_load(ld / "reviews"), key=lambda t: (-int(str(t[1].get("week", 0)) or 0) if str(t[1].get("week", "")).isdigit() else 0, t[0].name))
    cur_wk = None
    for p, fm in revs:
        wk = str(fm.get("week", "?"))
        if wk != cur_wk:
            r_lines += ["", f"## Week {wk}"]
            cur_wk = wk
        bits = [f"{k.replace('_rating', '')} {fm[k]}" for k in ("price_rating", "product_rating", "service_rating", "atmosphere_rating", "overall_rating") if fm.get(k) not in (None, "")]
        r_lines.append(f"- {L(p.stem)}: \"{str(fm.get('review_text', ''))[:160]}\" ({fm.get('theme', 'untagged')}" + (f"; {', '.join(bits)}" if bits else "") + ")")
    if not revs:
        r_lines.append("None recorded yet.")
    _write(v, "hub-reviews", "Customer reviews", "Every customer review shown.", r_lines)

    # ---- capital, loans, investments, acquisitions ----
    k_lines = ["# Capital, loans, investments and acquisitions", ""]
    for folder, heading in (("capital-allocation", "Capital allocation"), ("loans", "Loans"), ("investments", "Investments"), ("acquisitions", "Acquisitions")):
        items = _load(ld / folder)
        k_lines.append(f"## {heading} ({len(items)})")
        for p, fm in items:
            ment = reg.mentions(_text(fm), exclude=p.stem)
            k_lines.append(f"- {L(p.stem)}: " + (f"cash {_fmt(fm['required_cash'])}. " if fm.get("required_cash") else "") + (f"Mentions: {', '.join(L(m) for m in ment)}." if ment else ""))
        k_lines.append("")
    _write(v, "hub-capital", "Capital, loans, investments and acquisitions", "Money decisions and their records.", k_lines)

    # ---- stores (dossier per store) ----
    s_lines = ["# Stores", ""]
    for slug, d in sorted(reg.stores.items()):
        s_lines.append(f"- {L(slug, d['name'])}")
        merged = {}
        for p, fm in chron([(q, read_page(q)[0]) for q in d["notes"]]):
            merged.update({k: val for k, val in fm.items() if k not in META and val not in (None, "")})
        lines = [f"# {d['name']}", "", "Dossier: everything filed about this store. Generated.", "", "## Facts (latest values)"]
        lines += [f"- {k.replace('_', ' ')}: {_fmt(val)}" for k, val in merged.items()]
        lines += ["", "## Store records"] + [f"- {L(p.stem)}" for p in d["notes"]]
        lines += ["", "## Built options"]
        for p, fm, name in reg.catalog_rows:
            if (str(fm.get("category")), name.lower()) in chosen and name.lower() in {str(x).lower() for x in merged.values()}:
                lines.append(f"- {L(p.stem, name)} ({fm.get('category')})")
        rel = {"decisions": [], "capital": [], "events": []}
        for folder, key in (("decisions", "decisions"), ("capital-allocation", "capital"), ("events", "events")):
            for p, fm in _load(ld / folder):
                if any(a in _text(fm).lower() for a in reg.store_aliases(d["name"])):
                    rel[key].append(p)
        for key, heading in (("decisions", "Decisions mentioning it"), ("capital", "Capital records"), ("events", "Events mentioning it")):
            lines += ["", f"## {heading}"] + ([f"- {L(p.stem)}" for p in rel[key]] or ["- none"])
        city = str(merged.get("city", "")).lower()
        lines += ["", "## Elsewhere", "- " + L("hub-stores"), "- " + L("hub-weeks"), "- " + L("hub-catalog")]
        if city in reg.cities:
            lines.append("- " + L("hub-cities"))
        _write(v, slug, d["name"], f"Dossier for {d['name']}.", lines)
    _write(v, "hub-stores", "Stores", "All stores and their dossiers.", s_lines or ["# Stores", "", "None yet."])

    # ---- cities and competitors ----
    ci = ["# Cities", ""]
    for key, d in sorted(reg.cities.items()):
        ci.append(f"## {d['name']}")
        ci += [f"- {L(p.stem)}" for p in d["notes"]]
        ci += [f"- Store: {L(slug, sd['name'])}" for slug, sd in reg.stores.items()
               if str((read_page(sd['notes'][0])[0] or {}).get("city", "")).lower() == key]
        ci.append("")
    _write(v, "hub-cities", "Cities", "All cities.", ci)
    co = ["# Competitors", ""]
    for key, d in sorted(reg.competitors.items()):
        co.append(f"## {d['name']}")
        co += [f"- {L(p.stem)}" for p in d["notes"]]
        co += [f"- Event: {L(p.stem)}" for p, fm in _load(ld / "events") if key in _text(fm).lower()]
        co.append("")
    _write(v, "hub-competitors", "Competitors", "All competitors.", co)

    # ---- corrections ----
    co_lines = ["# Corrections", "", "Things that were filed and later turned out wrong or out of date. History stays; these override it.", ""]
    for p, fm in reversed(corrections.notes(v)):
        co_lines.append(f"## {L(p.stem, str(fm.get('claim'))[:80])}")
        co_lines.append(f"- True: {fm.get('correction')}")
        co_lines += [f"- Affected: {L(s)}" for s in (fm.get("affected") or [])]
        co_lines.append("")
    if len(co_lines) == 4:
        co_lines.append("None yet.")
    _write(v, "hub-corrections", "Corrections", "Corrections to earlier records.", co_lines)

    # ---- knowledge base and research ----
    kn = ["# Knowledge base", "", "One page per game system, with sourced findings labeled by the toolchain.", ""]
    for p in sorted((v / "wiki" / "knowledge-base").glob("*.md")):
        text = p.read_text(encoding="utf-8")
        kn.append(f"- {L(p.stem)}: {text.count('### Update')} research updates")
    kn += ["", "## Research (raw)"] + [f"- {L(p.stem)}" for p in sorted((v / "raw" / "research").glob("*.md"))]
    kn += ["", "## In-game tests"] + ([f"- {L(p.stem)}" for p in sorted((v / "wiki" / "tests").glob("*.md"))] or ["- none yet"])
    _write(v, "hub-knowledge", "Knowledge base", "Game knowledge and research.", kn)

    # ---- process decisions ----
    pr = ["# Process decisions", "", "Why the toolchain works the way it does, in order.", ""]
    pr += [f"- {L(p.stem)}: {(read_page(p)[0] or {}).get('summary', '')}" for p in sorted((v / "wiki" / "decisions").glob("*.md"))]
    _write(v, "hub-process", "Process decisions", "Process decision notes.", pr)

    # ---- rules and documents ----
    ru = ["# Rules and documents", "", "The CFO's rules, generated from the master prompt, and the top-level documents.", "", "## Core rules"]
    core = sorted((v / "core").glob("*.md"))
    ru += [f"- {L(p.stem)}" for p in core]
    ru += ["", "## Playbooks"] + [f"- {L(p.stem)}" for p in sorted((v / "core" / "playbooks").glob("*.md"))]
    ru += ["", "## Top-level documents"] + [f"- {L(n)}" for n in ("README", "SCHEMA", "CLAUDE", "AGENTS", "ARCHITECTURE", "CONTRIBUTING-AI") if (v / f"{n}.md").exists()]
    ru += ["", "## Source"] + [f"- {L(p.stem)}" for p in sorted((v / "raw" / "assets").glob("*.md"))]
    ru += ["", "## Exports"] + [f"- {L(p.stem)}" for p in sorted((v / "exports").glob("*.md"))]
    _write(v, "hub-rules", "Rules and documents", "Rules and top-level documents.", ru)

    # ---- archive and working files ----
    ar = ["# Archive and working files", "", "## Answers filed (raw)"]
    for sub in ("answers", "gem-answers"):
        ar += [f"- {L(p.stem)}" for p in sorted((v / "raw" / sub).glob("*.md"))]
    ar += ["", "## Notes filed (raw)"] + [f"- {L(p.stem)}" for p in sorted((v / "raw" / "notes").glob("*.md"))]
    ar += ["", "## Generated outputs"] + [f"- {L(p.stem)}" for p in sorted((v / "wiki" / "outputs").glob("*.md"))]
    ar += ["", "## Working files"] + [f"- {L(p.stem)}" for p in sorted((v / "inbox").glob("*.md"))]
    ar += ["", "## Ledger running tables"] + [f"- {L(p.stem)}" for p in sorted(ld.glob("*.md"))]
    _write(v, "hub-archive", "Archive and working files", "Raw archive, generated outputs, working files.", ar)

    # ---- map ----
    latest = briefs[-1].stem if briefs else None
    mp = ["# Vault map", "", "Start here. Every page in the vault is reachable from this map.", "", "## Hubs"]
    mp += [f"- {L(stem, title)}" for stem, title in HUB_TITLES.items()]
    mp += ["", "## Daily"] + [f"- {L(n)}" for n in ("HOME", "STATUS", "index", "log") if (v / f"{n}.md").exists() or (v / "wiki" / f"{n}.md").exists()]
    if latest:
        mp += ["", "## Latest briefing", f"- {L(latest)}"]
    _write(v, "map", "Vault map", "Top of the vault: links every hub.", mp)


def reachable_from_map(v: Path):
    """Set of md paths reachable from wiki/hubs/map.md following [[links]] (Obsidian-style stem matching)."""
    files = list(md_files(v))
    by_stem = {}
    for p in files:
        by_stem.setdefault(p.stem.lower(), p)
    fence = re.compile(r"```.*?```", re.S)
    link = re.compile(r"!?\[\[([^\]|#]+)")
    start = v / HUB_DIR / "map.md"
    if not start.exists():
        return set(), files
    seen, stack = set(), [start]
    while stack:
        p = stack.pop()
        if p in seen:
            continue
        seen.add(p)
        for m in link.finditer(fence.sub("", p.read_text(encoding="utf-8", errors="replace"))):
            q = by_stem.get(m.group(1).strip().split("/")[-1].lower())
            if q and q not in seen:
                stack.append(q)
    return seen, files
